# Site settings
title: Koala工作室
header-img: "img/Xacebook.jpg"
tagline: "cn"  
description: "MatrixXT|写作·安放心灵"  
baseurl: ""

# About/contact
owner: 
  name: " MatrixXT"
  email: 164640966@qq.com
  bio: "写作·安放心灵"

# Data
gavatar: http://wx4.sinaimg.cn/thumb300/006kKN9zly1fd45mnl0bsj31kw1z44i9.jpg
favicon: img/favicon.png

douban_username:  Doug
github_username: MatrixXT
facebook_username: Ting Xie
zhihu_username: Doug

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "MatrixXT"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disqus
  duoshuo :
    short_name : MatrixXT
  disqus :
      short_name : MatrixXT

# Analytics and webmaster tools stuff goes here
google_analytics: UA-80884545-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation